### ISSUE TITLE
requirements.txt file in Sphinx projects

### ISSUE THREAD

**Issue by meker12** [deconst/preparer-sphinx#47]
If a Sphinx project in a docs repository has a requirements.txt file, will Sphinx ignore it? @ktbartholomew  or @smashwilson 

Asking because I want to add a requirements.txt file to the repos to simplify local Sphinx set up for anyone that clones.  Similar to what OpenStack does, and also ObjectRocket.  

```
Activate your favorite virtualenv or pyenv, and do the following from your terminal:

pip install -r requirements.txt
cd source
make clean html

Your newly built HTML will live under _build/html/. To open the newly built documentation, execute open _build/html/index.html to see the root page.

Run make clean html or just make html from the source directory whenever you need a new build of the docs.
```

**Comment by smashwilson** [comment]
It does not, yet, but we already have an open issue for it as deconst/deconst-docs#106. The Jekyll build already respects dependencies from a Gemfile but I haven't gotten around to implementing the equivalent for this preparer yet.

How urgently do you need this?

**Comment by meker12** [comment]
Soon so we can provide easy set up for contributors similar to https://github.com/objectrocket/documentation#building-the-docs

Used this requirements.txt set up for the internal docs gh-pages builds, and it works great.

**Comment by smashwilson** [comment]
Wait, do you mean a `requirements.txt` file to install _Sphinx_, for builds you do on your laptops? You can do that right now; it won't hurt the preparer. Just add the file and a note to the README telling people to `pip install` before they run `make`.

The Deconst preparer will need to respect it if you use the requirements file to install things like Sphinx extensions from PyPi (instead of vendoring them). We definitely want that eventually, but I thought you were vendoring your extensions instead for the moment.

**Comment by meker12** [comment]
Yes requirements.txt for local builds.  -- Cool.  I will do so to help dev

What do you mean by "vendoring" 

For context:  Here is the contents of the requirements.txt file that I'm using for internal docs:

```
Jinja2==2.7.2
MarkupSafe==0.18
Pygments==1.6
Sphinx==1.3.1
docutils==0.11
sphinx_rtd_theme
```

**Comment by smashwilson** [comment]
> What do you mean by "vendoring"

Vendoring is the practice of distributing dependencies for a project by copying the files into the repository directly and checking them in to version control. It's what [Sphinx seems to advocate](http://www.sphinx-doc.org/en/stable/extensions.html#where-to-put-your-own-extensions) for installing dependencies, although personally I'm not fond of the technique.

From your requirements file, it looks like the only non-Sphinx thing you need is the readthedocs theme, right? And that won't do anything in the Deconst preparer build, because our Sphinx builders ignore the layout to use the ones in the control repository, instead.

**Comment by meker12** [comment]
Because Sphinx is extensible, and it's quite likely that we will need additional extensions to the doc platform (so far the spelling checker and release notes extensions have surfaced), we'll likely need to have a requirements.txt file that can support any valid extension that can be used in a Sphinx project.

**Comment by smashwilson** [comment]
From rackerlabs/docs-rpc#331, it'd also be useful to install dependencies from a `tox.ini` file.

**Comment by kallimachos** [comment]
The tox.ini file can specify dependencies using 'deps = -r{toxinidir}/requirements.txt'. If we go that route, are there any downsides to moving all the deps out of tox.ini into a requirements.txt file in order to keep them all in one place?

**Comment by kallimachos** [comment]
Decided just to go ahead and do it:

https://github.com/rackerlabs/docs-rpc/pull/336
